### ISSUE TITLE
Multiple action items can be open at once

### ISSUE THREAD

**Issue by guyca** [wix/react-native-action-view#3]
Should this be disabled by the library? Or expose a `close` method which can be called on each open view when list is scrolled.

<img width="466" alt="screen shot 2016-10-26 at 3 35 16 pm" src="https://cloud.githubusercontent.com/assets/12352397/19726129/f925b822-9b91-11e6-974e-266001be48b8.png">

**Comment by LeoNatan** [comment]
Fixed
